app/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from app.models import User, Applicant, Employer, Job, JobApplication
from app import db

auth_bp = Blueprint('auth_bp', __name__)

@auth_bp.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get('password2')
        user_type = request.form.get('userType')

        new_user = User(
            name=name,
            email=email,
            password=generate_password_hash(password, method='pbkdf2:sha256'),
            user_type=user_type
        )
        db.session.add(new_user)
        db.session.commit()

        if new_user.user_type == 'applicant':
            applicant = Applicant(user_id=new_user.user_id)
            db.session.add(applicant)
            db.session.commit()
        else:
            employer = Employer(user_id=new_user.user_id)
            db.session.add(employer)
            db.session.commit()

        flash('Account created.', category='success')
        login_user(new_user, remember=True)
        return redirect(url_for('jobs_bp.home'))
    
    return render_template('register.html')

@auth_bp.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully.', category='success')
                login_user(user, remember=True)
                return redirect(url_for('jobs_bp.home'))
            else:
                flash('Incorrect password. Try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template('login.html')

@auth_bp.route('/log-out')
@login_required
def logout():
    logout_user()
    flash('Logged out successfully.', category='success')
    return redirect(url_for('jobs_bp.home'))

app/routes/dashboard.py
from flask import Blueprint, render_template, send_from_directory, current_app, request, redirect
from flask_login import login_required, current_user
from app import db
from app.models import User, Applicant, Employer, Job, JobApplication

dashboard_bp = Blueprint('dashboard_bp', __name__)

@dashboard_bp.route('/my-applications')
@login_required
def my_applications():
    user_job_applications = JobApplication.query.filter_by(applicant_id=current_user.user_id).order_by(JobApplication.application_date.desc()).all()
    return render_template('my_applications.html', user_job_applications=user_job_applications)

@dashboard_bp.route('/dashboard')
@login_required
def dashboard():
    user_job_posted = Job.query.filter_by(employer_id=current_user.user_id).order_by(Job.date_posted.desc()).all()
    return render_template('dashboard.html', user_job_posted=user_job_posted)

@dashboard_bp.route('/applicants/<int:job_id>')
@login_required
def view_applicants(job_id):
    applications = JobApplication.query.filter_by(job_id=job_id).order_by(JobApplication.application_date.desc()).all()
    return render_template('applicants.html', applications=applications, job=Job.query.filter_by(id=job_id).first())

@dashboard_bp.route('/update-status', methods=['POST'])
def update_status():
    application_id = request.form.get('application_id')
    new_status = request.form.get('status')

    application = JobApplication.query.get(application_id)
    if application:
        application.status = new_status
        db.session.commit()
    
    return redirect(request.referrer)

app/routes/jobs.py
from flask import Blueprint, render_template, request, redirect, flash, url_for, current_app
from flask_login import current_user, login_required
from datetime import datetime
import os
from app.models import User, Applicant, Employer, Job, JobApplication
from app import db
from app.utils import secure_unique_filename

jobs_bp = Blueprint('jobs_bp', __name__)

@jobs_bp.route('/')
@jobs_bp.route('/home')
def home():
    jobs = Job.query.order_by(Job.date_posted.desc()).all()
    return render_template('home.html', jobs=jobs)

@jobs_bp.route('/job-detail/<int:job_id>')
def job_detail(job_id):
    job = Job.query.get_or_404(job_id)
    if current_user.is_authenticated:
        user_job_applications = JobApplication.query.filter_by(applicant_id=current_user.user_id).order_by(JobApplication.application_date.desc()).all()
        
        if user_job_applications:
            for application in user_job_applications:
                if application.job.id == job_id:
                    return render_template('job_detail.html', job=job, isApplied=True)

    return render_template('job_detail.html', job=job, isApplied=False)

@jobs_bp.route('/post-job', methods=['POST', 'GET'])
@login_required
def post_job():
    if request.method == 'POST':
        title = request.form.get('title')
        description = request.form.get('description')
        requirements = request.form.get('requirements')
        location = request.form.get('location')
        salary_min = float(request.form.get('salary-min'))
        salary_max = float(request.form.get('salary-max'))

        new_job = Job(
            employer_id=current_user.user_id,
            title=title,
            description=description,
            requirements=requirements,
            location=location,
            salary_min=salary_min,
            salary_max=salary_max
        )
        db.session.add(new_job)
        db.session.commit()
        
        flash('Job Posted.', category='success')
        return redirect(url_for('dashboard_bp.dashboard'))
    
    return render_template('post_job.html', button_name='Post Job')

@jobs_bp.route('/apply/<int:job_id>', methods=['POST', 'GET'])
def job_apply(job_id):
    if request.method == 'POST':
        if 'file' not in request.files:
            flash('No file part', category='error')
        resume = request.files['resume']
        cover_letter = request.files['coverLetter']
        phone_number = request.form.get('number')

        if resume and cover_letter:
            unique_id = f'{current_user.user_id}_{job_id}'
            resume_filename = secure_unique_filename(resume.filename, unique_id)
            cover_letter_filename = secure_unique_filename(cover_letter.filename, unique_id)
            resume_filepath = os.path.join(current_app.config['UPLOAD_FOLDER_RESUME'], resume_filename)
            cover_letter_filepath = os.path.join(current_app.config['UPLOAD_FOLDER_COVER_LETTER'], cover_letter_filename)

            resume.save(resume_filepath)
            cover_letter.save(cover_letter_filepath)

            new_job_application = JobApplication(
                applicant_id=current_user.user_id,
                job_id=job_id,
                phone=phone_number,
                resume_path=f'uploads/resumes/{resume_filename}',
                cover_letter_path=f'uploads/cover_letter/{cover_letter_filename}',
                status='applied'
            )
            job = Job.query.filter_by(id=job_id).first()
            job.no_of_applicants += 1
            db.session.add(new_job_application)
            db.session.commit()
            flash('Applied successfully!', category='success')
            return redirect(url_for('jobs_bp.home'))
        else:
            flash('No files uploaded', category='error')

    return render_template('apply_job.html', email=current_user.email, name=current_user.name)

@jobs_bp.route('/edit-job/<int:job_id>', methods=['POST', 'GET'])
def job_edit(job_id):
    job = Job.query.filter_by(id=job_id).first()
    if request.method == 'POST':
        if job:
            job.title = request.form.get('title')
            job.description = request.form.get('description')
            job.requirements = request.form.get('requirements')
            job.location = request.form.get('location')
            job.salary_min = request.form.get('salary-min')
            job.salary_max = request.form.get('salary-max')
            job.date_updated = datetime.utcnow()
            
            db.session.commit()
            flash('Job Updated Successfully.', category='success')
            return redirect(url_for('jobs_bp.home'))
        else:
            flash('Job does not exist.', category='error')

    return render_template('post_job.html', title=job.title, description=job.description, requirements=job.requirements, location=job.location, salary_min=job.salary_min, salary_max=job.salary_max, button_name='Update Job')

@jobs_bp.route('/delete-job/<int:job_id>', methods=['POST'])
def job_delete(job_id):
    job = Job.query.filter_by(id=job_id).first()
    if job:
        db.session.delete(job)
        db.session.commit()
        flash('Job Deleted Successfully.', category='success')
    else:
        flash('Job not found.', category='error')

    return redirect(url_for('jobs_bp.home'))

app/routes/profile.py
from flask import Blueprint, render_template, send_from_directory, current_app, request, redirect
from flask_login import login_required, current_user
from app import db
from app.models import User, Applicant, Employer, Job, JobApplication

profile_bp = Blueprint('profile_bp', __name__)

@profile_bp.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

app/templates/applicants.html
{% extends 'base.html' %}

{% block title %}Applicants{% endblock %}

{% block content %}
<h2 align="center">List of Applicants</h2>
<h3 align="center">{{ job.title }}</h3>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr class="table-info">
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Resume</th>
                <th scope="col">Cover Letter</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for application in applications %}
            <tr>
                <td>{{ application.applicant.user.name }}</td>
                <td>{{ application.applicant.user.email }}</td>
                <td>{{ application.phone }}</td>
                <td>
                    {% if application.resume_path %}
                        <a href="{{ url_for('static', filename=application.resume_path) }}"
                        target="_blank">View Resume</a>
                    {% else %}
                        No Resume
                    {% endif %}
                </td>
                <td>
                    {% if application.cover_letter_path %}
                        <a href="{{ url_for('static', filename=application.cover_letter_path) }}"
                        target="_blank">View Cover Letter</a>
                    {% else %}
                        No Cover Letter
                    {% endif %}
                </td>
                <td>
                    <span id="status-display-{{ loop.index }}">{{ application.status.capitalize() }}</span>

                    <form method="post" action="{{ url_for('dashboard_bp.update_status') }}" class="d-none mt-1" id="status-form-{{ loop.index }}">
                        <input type="hidden" name="application_id" value="{{ application.id }}">
                        <select name="status" class="form-select form-select-sm mb-1">
                            <option value="applied" {% if application.status == 'applied' %}disabled selected{% endif %}>Applied</option>
                            <option value="accepted" {% if application.status == 'accepted' %}disabled selected{% endif %}>Accepted</option>
                            <option value="rejected" {% if application.status == 'rejected' %}disabled selected{% endif %}>Rejected</option>
                        </select>
                        <button type="submit" class="btn btn-sm btn-success">Save</button>
                        <button type="button" class="btn btn-sm btn-secondary" onclick="cancelEdit('{{ loop.index }}')">Cancel</button>
                    </form>
                </td>
                <td>
                    <button
                        class="btn btn-sm btn-outline-primary"
                        onclick="toggleEdit('{{ loop.index }}')"
                    >Edit Status</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
function toggleEdit(index){
    index = parseInt(index);
    const statusDisplay = document.getElementById(`status-display-${index}`);
    const statusForm = document.getElementById(`status-form-${index}`);

    statusDisplay.classList.add('d-none');
    statusForm.classList.remove('d-none');
}

function cancelEdit(index){
    index = parseInt(index);
    const statusDisplay = document.getElementById(`status-display-${index}`);
    const statusForm = document.getElementById(`status-form-${index}`);
    
    statusDisplay.classList.remove('d-none');
    statusForm.classList.add('d-none');
}
</script>
{% endblock %}

app/templates/apply_job.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title %}Apply Job{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
  <h3 align="center">Apply</h3>
  <div class="mb-3">
    <label for="name">Name</label>
    <input
      type="text"
      class="form-control"
      id="name"
      name="name"
      value="{{ name }}"
      readonly
    />
  </div>

  <div class="mb-3">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      value="{{ email }}"
      readonly
    />
  </div>

  <div class="mb-3">
    <label for="number">Phone Number</label>
    <input
      type="number"
      class="form-control"
      id="number"
      name="number"
      placeholder="Enter phone number"
      required
    />
  </div>

  <div class="mb-3">
    <label for="resume">Resume (.pdf file only)</label>
    <input
      type="file"
      class="form-control"
      id="resume"
      name="resume"
      accept=".pdf"
      required
    />
  </div>

  <div class="mb-3">
    <label for="coverLetter">Cover Letter (.pdf file only)</label>
    <input
      type="file"
      class="form-control"
      id="coverLetter"
      name="coverLetter"
      accept=".pdf"
      required
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="Home" href="/home">Home</a>

          {% if current_user.is_authenticated %}
            {% if current_user.user_type == 'applicant' %}
              <a class="nav-item nav-link" id="Home" href="/my-applications">My Applications</a>
            {% endif %}

            {% if current_user.user_type == 'employer' %}
              <a class="nav-item nav-link" id="Home" href="/dashboard">Dashboard</a>
              <a class="nav-item nav-link" id="Home" href="/post-job">Post Job</a>
            {% endif %}

            <a class="nav-item nav-link" id="Home" href="/log-out">Logout</a>
            <a class="nav-item nav-link" id="Profile" href="/profile">Profile</a>

          {% else %}
            <a class="nav-item nav-link" id="Home" href="/login">Login</a>
            <a class="nav-item nav-link" id="Home" href="/register">Register</a>
          {% endif %}
        </div>
      </div>
    </nav>

    <svg xmlns="http://www.w3.org/2000/svg" style="display: none">
      <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path
          d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"
        />
      </symbol>

      <symbol
        id="exclamation-triangle-fill"
        fill="currentColor"
        viewBox="0 0 16 16"
      >
        <path
          d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"
        />
      </symbol>
    </svg>

    {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
        {% for category, message in messages %}
          {% if category == 'success' %}
            <div class="alert alert-success alert-dismissible fade show d-flex align-items-center" role="alert">
              <svg
                class="bi flex-shrink-0 me-2"
                width="24"
                height="24"
                role="img"
                aria-label="Success:"
              >
                <use xlink:href="#check-circle-fill" />
              </svg>
              <div>{{ message }}</div>
              <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% else %}
            <div class="alert alert-danger alert-dismissible fade show d-flex align-items-center" role="alert">
              <svg
                class="bi flex-shrink-0 me-2"
                width="24"
                height="24"
                role="img"
                aria-label="Danger:"
              >
                <use xlink:href="#exclamation-triangle-fill" />
              </svg>
              <div>{{ message }}</div>
              <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="container">{% block content %}{% endblock %}</div>

    <!-- Bootstrap JS bundle -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  </body>
</html>

app/templates/dashboard.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title %}Dashboard{% endblock %}

{% block content %}
{% if user_job_posted %}
    <h2 align="center">List of Job Posted</h2>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr class="table-info">
                    <th scope="col">Job Title</th>
                    <th scope="col">Date Posted</th>
                    <th scope="col">Date Updated</th>
                    <th scope="col">No. of Applicants</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                    {% for job in user_job_posted %}
                    <tr>
                        <td>{{ job.title }}</td>
                        <td>{{ job.date_posted }}</td>
                        <td>{{ job.date_updated }}</td>
                        <td>{{ job.no_of_applicants }}</td>
                        <td>
                            <a
                                href="{{ url_for('jobs_bp.job_detail', job_id=job.id) }}"
                                class="btn btn-sm btn-outline-primary"
                                >View Job Details</a
                            >
                            <a
                                href="{{ url_for('dashboard_bp.view_applicants', job_id=job.id) }}"
                                class="btn btn-sm btn-outline-primary"
                                >View Applicants</a
                            >
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <h2 align="center">No Job Posted.</h2>
{% endif %}
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h2 align="center">Latest Jobs</h2>
{% for job in jobs %}
    {% include 'components/job_card.html' %}
{% endfor %}
{% endblock %}

app/templates/job_detail.html
{% extends 'base.html' %}

{% block title %}Job Details{% endblock %}

{% block content %}
<div class="container mt-4">
  <div class="card shadow-sm border-0">
    <div class="card-body">
      <h3 class="card-title text-center mb-4">{{ job.title }}</h3>

      <div class="mb-3">
        <strong>Description:</strong>
        <p class="text-muted">{{ job.description }}</p>
      </div>

      <div class="mb-3">
        <strong>Requirements:</strong>
        <p class="text-muted">{{ job.requirements }}</p>
      </div>

      <div class="mb-3">
        <strong>Location:</strong>
        <span class="badge badge-secondary text-dark">{{ job.location }}</span>
      </div>

      <div class="mb-3">
        <strong>Salary:</strong>
        <span class="badge badge-light text-dark">
          ₱{{ '{:,g}'.format(job.salary_min) }} - {{ '{:,g}'.format(job.salary_max) }}
        </span>
      </div>

      <div class="mb-3">
        <strong>Date Posted:</strong>
        <span class="badge badge-light text-dark">{{ job.date_posted.date() }}</span>
      </div>

      {% if job.date_updated is not none %}
        <div class="mb-3">
          <strong>Date Updated:</strong>
          <span class="badge badge-light text-dark">{{ job.date_updated.date() }}</span>
        </div>
      {% endif %}

    {% if current_user.is_authenticated %}
      {% if current_user.user_type == 'applicant' %}
        {% if isApplied == False %}
          <a href="{{ url_for('jobs_bp.job_apply', job_id=job.id) }}" class="btn btn-sm btn-outline-primary">Apply</a>
        {% else %}
          <span class="badge bg-success">Already Applied</span>
        {% endif %}
      {% endif %}

      {% if current_user.user_type == 'employer' %}
        {% if current_user.user_id == job.employer_id %}
          <form method="post" action="{{ url_for('jobs_bp.job_delete', job_id=job.id) }}" onsubmit="return confirm('Are you sure you want to delete this job?');">
            <a href="{{ url_for('jobs_bp.job_edit', job_id=job.id) }}" class="btn btn-sm btn-outline-warning">Edit</a>
            <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
          </form>
        {% else %}
          <span class="badge bg-info">You can't apply here</span>
        {% endif %}
      {% endif %}

      {% else %}
        <a href="{{ url_for('auth_bp.login') }}" class="btn btn-sm btn-outline-primary">Apply</a>
    {% endif %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title %}Login{% endblock %}

<!-- prettier-ignore -->
{% block content %}
<form method="post">
  <h3 align="center">Login</h3>
  <div class="mb-3">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>

  <div class="mb-3">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

app/templates/my_applications.html
{% extends 'base.html' %}

{% block title %}Job Applications{% endblock %}

{% block content %}
{% if user_job_applications %}
    <h2 align="center">List of Job Applications</h2>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr class="table-info">
                    <th scope="col">Job Title</th>
                    <th scope="col">Application Date</th>
                    <th scope="col">Phone</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for application in user_job_applications %}
                    <tr>
                        <td>{{ application.job.title }}</td>
                        <td>{{ application.application_date }}</td>
                        <td>{{ application.phone }}</td>
                        <td>{{ application.status.capitalize() }}</td>
                        <td>
                            <a
                                href="{{ url_for('jobs_bp.job_detail', job_id=application.job.id) }}"
                                class="btn btn-sm btn-outline-primary"
                                >View Details</a
                            >
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <h2 align="center">You have no Job Applications.</h2>
{% endif %}
{% endblock %}

app/templates/post_job.html
{% extends 'base.html' %}

{% block title %}Post Job{% endblock %}

{% block content %}
<form method="post">
  <h3 align="center">Post Job</h3>
  <div class="mb-3">
    <label for="title">Title</label>
    <input
      type="text"
      class="form-control"
      id="title"
      name="title"
      placeholder="Enter job title"
      value="{{ title or '' }}"
      required
    />
  </div>

  <div class="mb-3">
    <label for="description">Description</label>
    <textarea
      class="form-control"
      id="description"
      name="description"
      rows="4"
      placeholder="Provide a detailed job description"
      required
    >{{ description or '' }}</textarea>
  </div>

  <div class="mb-3">
    <label for="requirements">Requirements</label>
    <textarea
      class="form-control"
      id="requirements"
      name="requirements"
      rows="3"
      placeholder="List required skills, experience, or qualifications"
      required
    >{{ requirements or '' }}</textarea>
  </div>

  <div class="mb-3">
    <label for="location">Location</label>
    <input
      type="text"
      class="form-control"
      id="location"
      name="location"
      placeholder="Enter job location or address"
      value="{{ location or '' }}"
      required
    />
  </div>

  <div class="mb-3">
    <label for="salary_min">Salary Range</label>
    <div class="d-flex gap-2">
      <input
        type="number"
        class="form-control"
        id="salary-min"
        name="salary-min"
        placeholder="Minimum"
        min="0"
        value="{{ salary_min or '' }}"
        required
      />
      <input
        type="number"
        class="form-control"
        id="salary-max"
        name="salary-max"
        placeholder="Maximum"
        min="0"
        value="{{ salary_max or '' }}"
        required
      />
    </div>
  </div>
  <br />
  <button type="submit" class="btn btn-primary">{{ button_name }}</button>
</form>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}

{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title %}Register{% endblock %}

<!-- prettier-ignore -->
{% block content %}
<form method="post">
  <h3 align="center">Register</h3>
  <div class="mb-3">
    <label for="name">Name</label>
    <input
      type="text"
      class="form-control"
      id="name"
      name="name"
      placeholder="Enter name"
    />
  </div>

  <div class="mb-3">
    <label for="">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>

  <div class="mb-3">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>

  <div class="mb-3">
    <label for="password2">Re-enter Password</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Re-enter password"
    />
  </div>

  <div class="mb-3">
    <label for="userType">User Type</label>
    <div class="form-check">
      <input
        class="form-check-input"
        type="radio"
        name="userType"
        id="applicant"
        value="applicant"
      />
      <label class="form-check-label" for="applicant"> Applicant </label>
    </div>
    <div class="form-check">
      <input
        class="form-check-input"
        type="radio"
        name="userType"
        id="employer"
        value="employer"
        checked
      />
      <label class="form-check-label" for="employer"> Employer </label>
    </div>
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}